global:
  govcloud: true
  marketplace-ami: true
  owner: quickstart@amazon.com
  qsname: quickstart-trendmicro-deepsecurity
  regions:
    - us-east-1
  reporting: true
tests:
  test-deepsec:
    parameter_input: inputs.json
    template_file: quickstart/trendmicro-deepsecurity-vpc.template
